% Generated by ADiMat 0.6.8-5613 (192c5fe7)
% © 2001-2008 Andre Vehreschild <vehreschild@sc.rwth-aachen.de>
% © 2009-2018 Johannes Willkomm <johannes@johannes-willkomm.de>
% TU Darmstadt, 64289 Darmstadt, Germany
% Visit us on the web at https://ai-and-it.de/adimat/
% Report bugs to jwillkomm@ai-and-it.de
%
%                             DISCLAIMER
% 
% ADiMat was prepared as part of an employment at the Institute for Scientific Computing,
% RWTH Aachen University, Germany and at the Institute for Scientific Computing,
% TU Darmstadt, Germany and is provided AS IS. 
% NEITHER THE AUTHOR(S), THE GOVERNMENT OF THE FEDERAL REPUBLIC OF GERMANY
% NOR ANY AGENCY THEREOF, NOR THE RWTH AACHEN UNIVERSITY, NOT THE TU DARMSTADT,
% INCLUDING ANY OF THEIR EMPLOYEES OR OFFICERS, MAKES ANY WARRANTY, EXPRESS OR IMPLIED,
% OR ASSUMES ANY LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS,
% OR USEFULNESS OF ANY INFORMATION OR PROCESS DISCLOSED, OR REPRESENTS THAT ITS USE
% WOULD NOT INFRINGE PRIVATELY OWNED RIGHTS.
%
% Parameters:
%  - dependents=y
%  - independents=a, b
%  - inputEncoding=ISO-8859-1
%
% Functions in this file: a_Test_Function, rec_Test_Function,
%  ret_Test_Function
%

function [a_a a_b nr_y] = a_Test_Function(a, b, a_y)
   tmpca1 = sqrt(b);
   y = a + tmpca1;
   nr_y = y;
   [a_tmpca1 a_a a_b] = a_zeros(tmpca1, a, b);
   if nargin < 3
      a_y = a_zeros1(y);
   end
   a_a = adimat_adjsum(a_a, adimat_adjred(a, a_y));
   a_tmpca1 = adimat_adjsum(a_tmpca1, adimat_adjred(tmpca1, a_y));
   a_b = adimat_adjsum(a_b, 0.5 .* a_tmpca1./sqrt(b));
end

function y = rec_Test_Function(a, b)
   tmpca1 = sqrt(b);
   y = a + tmpca1;
   adimat_push(tmpca1, y, a, b);
end

function [a_a a_b] = ret_Test_Function(a_y)
   [b a y tmpca1] = adimat_pop;
   [a_tmpca1 a_a a_b] = a_zeros(tmpca1, a, b);
   if nargin < 1
      a_y = a_zeros1(y);
   end
   a_a = adimat_adjsum(a_a, adimat_adjred(a, a_y));
   a_tmpca1 = adimat_adjsum(a_tmpca1, adimat_adjred(tmpca1, a_y));
   a_b = adimat_adjsum(a_b, 0.5 .* a_tmpca1./sqrt(b));
end
% a = [9 1 6];
% b = [2 5 3];
% % compute Jacobian via forward-mode
% J = admDiffFor(@f, 1, a, b)
% % compute Jacobian via reverse-mode
% Jrev = admDiffRev(@f, 1, a, b)
% setenv ADIMAT_SERVER https://adimat.de/adimat/transform/
